### ISSUE TITLE
Unable to configure registration with external platform due to requiring platform_key_chain

### ISSUE THREAD

**Issue by ionparticle** [oat-sa/bundle-lti1p3#48]
An external platform using JWKS doesn't need a key chain, but if you leave the platform_key_chain config out, you get an 500 error complaining about undefined array key "platform_key_chain".

**Comment by ekkinox** [comment]
Hello @ionparticle

Thx for feedback.

You can configure an external platform that provided only JWKS, this way:

```
    registrations:
        example:
            client_id: "client_id"
            platform: "externalPlatform"
            tool: "myTool"
            deployment_ids:
                - "1"
                - "2"
            platform_key_chain: null
            tool_key_chain: "toolKey"
            platform_jwks_url: "https://external-platform/.well-known/jwks"
            tool_jwks_url: "https://my-tool/lti1p3/.well-known/jwks/toolSet.json"
```

I think it's because you removed the `platform_key_chain` instead of putting it to null (as in example above)

Also, if you need more details how this bundle internally works with JWKS vs key files, [you can check here](https://github.com/oat-sa/lib-lti1p3-core/blob/master/doc/quickstart/configuration.md#public-key-versus-jwks).

Can you confirm it works with  `platform_key_chain: null` ?  

If yes, let me know so we can close this issue .
